# Generated by Django 5.2.15 on 2026-09-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('backend', 'Backend'), ('devops', 'DevOps'), ('network', 'Network')], default='backend', help_text='Which role page (and later, which Backend City district) shows this project.', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='ended_on',
            field=models.DateField(blank=True, help_text='Leave empty while the project is ongoing (shown as PRESENT).', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='started_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(help_text='Comma-separated, e.g. "Python, Django, PostgreSQL".', max_length=300),
        ),
    ]
