# Generated by Django 5.2.15 on 2026-09-26 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_category_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='architecture',
            field=models.TextField(blank=True, default='', help_text='One step per line: Title | Tech | Description'),
        ),
        migrations.AddField(
            model_name='project',
            name='decisions',
            field=models.TextField(blank=True, default='', help_text='One per line: Title | Description'),
        ),
        migrations.AddField(
            model_name='project',
            name='features',
            field=models.TextField(blank=True, default='', help_text='One feature per line.'),
        ),
        migrations.AddField(
            model_name='project',
            name='metrics',
            field=models.TextField(blank=True, default='', help_text='One per line: Label | Value'),
        ),
        migrations.AddField(
            model_name='project',
            name='problem',
            field=models.TextField(blank=True, default='', help_text='"The Engineering Challenge" paragraph.'),
        ),
        migrations.AddField(
            model_name='project',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='projects.project')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
