# Generated by Django 5.2.15 on 2026-09-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_case_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('backend', 'Backend'), ('devops', 'DevOps'), ('network', 'Network')], default='backend', help_text='Which role page and which Backend City district show this project.', max_length=20),
        ),
    ]
